### PR TITLE
Add helper (1)

### PR DESCRIPTION
**Pull request by fstrub95**
I updated the database to make it easier to use. What do you mean by Guess table?

I implemented the key functions. The design is still clumsy and I should improve it soon.
I have other idea such as : 
- quit_dialogue -> remove dialogue
- cloture_dialogue -> cannot append more questions
- get_unfinished_dialogue
- valid_hits_for_worker

More importantly, I optimized the SQL request to retrieve pictures with the annotations.

fully tested on the db, it should work smoothly

Cheers, 
Florian

### CODE REVIEW

**Comment by harm-devries** [comment]
The current workflow is as follows: after an x number of questions the questioner clicks a button to start guessing the object. Then all object segmentations are shown in the image, and he clicks on the right object. So, we want to save the guess of the questioner - I couldn't find a table for that in the database graph. Did I miss it?

By the way, can you make sure that your code is PEP8 - see https://www.python.org/dev/peps/pep-0008/? When working with multiple people I am trying to make sure we keep a good coding style. Most editors have a plugin to point you to pep8 warnings or can even autocorrect your code.

**Comment by harm-devries** [comment]
Oh.. and you didn't update the database fill script?

**Comment by fstrub95** [comment]
Is it not working? I'll fix it tomorrow morning, I may forgot to commit a fix. OK for pep08, I just hate the constraint regarding the blank line.
Ok for the Workflow. I have to change the start_conversation method and update the database. + add insert new guess.

**Comment by harm-devries** [comment]
I didn't test it yet. But I saw some changes in .sql scheme so I was expecting changes in the database filler as well. 

Great, I have a more thorough look later

**Pull request merged**
